name: Run Tests

on: [push]

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install pytest and plugins
        run: pip install pytest pytest-describe pytest-spec pytest-mock
      - name: Run unit tests
        run: pytest test_brute.py --spec
        
  RunFunctionalTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install dependencies
        run: pip install behave selenium behave-webdriver
      - name: Run functional tests
        run: behave features/