name: Run Tests

on: [push]

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install pytest and plugins
        run: |
          pip install pytest==8.3.4 
          pip install pytest-describe==2.2.0 
          pip install pytest-spec 
          pip install pytest-mock
      - name: Run unit tests
        run: pytest test_brute.py --spec
        
  RunFunctionalTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install dependencies
        run: |
          pip install selenium==3.141.0
          pip install behave==1.2.6
          pip install behave-webdriver==0.3.1
      - name: Run functional tests
        run: behave features/